export { default as DocumentDisplay } from './DocumentDisplay.vue'
export { default as MultiSearchPopover2 } from './MultiSearchPopover2.vue'
export { default as IndexSwitcher } from './IndexSwitcher.vue'
export { default as DocumentList } from './DocumentList.vue'
export { default as Screen } from './Screen.vue'